{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.71.aar",
          "url": "netsdk-1.0.1.71.aar",
          "size": 3299096,
          "sha512": "abc1e959878983f66ae58958309b9056d261ab2354cd2070f9fdca9799308390d69fe8f9ee2a6505951ee0a993c545b32f3f03d7e317db21a0eb47148c34423c",
          "sha256": "fea2f397c5655fa2bd4aa0cb772f51b5ce2d2c854ea7042a18f85f279552f6e9",
          "sha1": "ccc466e56be3b2cc540be1ce4d61bef853a16840",
          "md5": "c356b86199fdb1ac011d2878b4bf9dfe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.71.aar",
          "url": "netsdk-1.0.1.71.aar",
          "size": 3299096,
          "sha512": "abc1e959878983f66ae58958309b9056d261ab2354cd2070f9fdca9799308390d69fe8f9ee2a6505951ee0a993c545b32f3f03d7e317db21a0eb47148c34423c",
          "sha256": "fea2f397c5655fa2bd4aa0cb772f51b5ce2d2c854ea7042a18f85f279552f6e9",
          "sha1": "ccc466e56be3b2cc540be1ce4d61bef853a16840",
          "md5": "c356b86199fdb1ac011d2878b4bf9dfe"
        }
      ]
    }
  ]
}
