{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.2.81",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.2.81.aar",
          "url": "netsdk-1.0.2.81.aar",
          "size": 3313556,
          "sha512": "1dfdbd091090dbe69fa6d582ee6ec643ccd06d83104dffe090e93aadefcdc6fe2acf31fc81785d41ff0650af84427594c9eb28b128b96f2ec161d09ddd1ce396",
          "sha256": "c7e4d693e6a01a140ed16a12933ba1db417f50786f7d2a055dabed72b6ff198d",
          "sha1": "564dba508fabcb7470d7727b3591af828943e3d7",
          "md5": "e0029b6301302c8f8eca35c5f4f64251"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.2.81.aar",
          "url": "netsdk-1.0.2.81.aar",
          "size": 3313556,
          "sha512": "1dfdbd091090dbe69fa6d582ee6ec643ccd06d83104dffe090e93aadefcdc6fe2acf31fc81785d41ff0650af84427594c9eb28b128b96f2ec161d09ddd1ce396",
          "sha256": "c7e4d693e6a01a140ed16a12933ba1db417f50786f7d2a055dabed72b6ff198d",
          "sha1": "564dba508fabcb7470d7727b3591af828943e3d7",
          "md5": "e0029b6301302c8f8eca35c5f4f64251"
        }
      ]
    }
  ]
}
