{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.75",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.75.aar",
          "url": "netsdk-1.0.1.75.aar",
          "size": 3303860,
          "sha512": "b8132d81bb59b05bce765e4ca2cff87ec86033aa370a91ca8238a19f410f5545abf8f963b1a3dd2dbbc9e148c298816a0f1b93f5edd9feecfd0668c6ded48b42",
          "sha256": "dedece4cfec1e8f630a7c4c1d477c8278d3b7b26ceced99c3123b9af948e067b",
          "sha1": "d0c0e46aa2c21c2d3f8f9faf13db2b787efe2799",
          "md5": "2fd86681c41a6b5eeb0fce31106a7877"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.75.aar",
          "url": "netsdk-1.0.1.75.aar",
          "size": 3303860,
          "sha512": "b8132d81bb59b05bce765e4ca2cff87ec86033aa370a91ca8238a19f410f5545abf8f963b1a3dd2dbbc9e148c298816a0f1b93f5edd9feecfd0668c6ded48b42",
          "sha256": "dedece4cfec1e8f630a7c4c1d477c8278d3b7b26ceced99c3123b9af948e067b",
          "sha1": "d0c0e46aa2c21c2d3f8f9faf13db2b787efe2799",
          "md5": "2fd86681c41a6b5eeb0fce31106a7877"
        }
      ]
    }
  ]
}
