{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.70.aar",
          "url": "netsdk-1.0.1.70.aar",
          "size": 3299094,
          "sha512": "fa600d47e511f4df0d1164f2db84b952a00cf53b6958234864096e70ed549b7e4e117c92cea7bb9254f45db915d7b4c2eb72a7991290e29ead6b4584bf3e396a",
          "sha256": "555cc3c90b81c4066e7b832cfce61ba38a7045e3b1a5c9d2ef3b67f6cf05ebcf",
          "sha1": "59c4778a22eabbc0688f505bc9bf73f2b4f41990",
          "md5": "484c589550e217067cf83cf5a142bd05"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.70.aar",
          "url": "netsdk-1.0.1.70.aar",
          "size": 3299094,
          "sha512": "fa600d47e511f4df0d1164f2db84b952a00cf53b6958234864096e70ed549b7e4e117c92cea7bb9254f45db915d7b4c2eb72a7991290e29ead6b4584bf3e396a",
          "sha256": "555cc3c90b81c4066e7b832cfce61ba38a7045e3b1a5c9d2ef3b67f6cf05ebcf",
          "sha1": "59c4778a22eabbc0688f505bc9bf73f2b4f41990",
          "md5": "484c589550e217067cf83cf5a142bd05"
        }
      ]
    }
  ]
}
