{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.78",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.78.aar",
          "url": "netsdk-1.0.1.78.aar",
          "size": 3299882,
          "sha512": "737b9721504760b6eeadb00c936d27b07269ce0003bc12bce999f4add80d563710f5cc04ff8b16a344bc23256fd3782085b3af5e6d553e1d599913c6a02630ce",
          "sha256": "9a58ca4f47624455772edae622d64aa98a3ef19e01d1b04cd416a8b41d01d6bb",
          "sha1": "7c8701d15aeb43986b455c7ea14ffc367cc7fb65",
          "md5": "cd56cd97cbc803b152e26de746633e14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.78.aar",
          "url": "netsdk-1.0.1.78.aar",
          "size": 3299882,
          "sha512": "737b9721504760b6eeadb00c936d27b07269ce0003bc12bce999f4add80d563710f5cc04ff8b16a344bc23256fd3782085b3af5e6d553e1d599913c6a02630ce",
          "sha256": "9a58ca4f47624455772edae622d64aa98a3ef19e01d1b04cd416a8b41d01d6bb",
          "sha1": "7c8701d15aeb43986b455c7ea14ffc367cc7fb65",
          "md5": "cd56cd97cbc803b152e26de746633e14"
        }
      ]
    }
  ]
}
