{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.63.aar",
          "url": "netsdk-1.0.1.63.aar",
          "size": 3294564,
          "sha512": "9976eb2fea9503cc20140be99a6191d9425343e32e627468f61eeb8441ad0e09260f3eaedb254ec3dc853dc8b8a8e6702579ba8d289f82407098aa59ff031373",
          "sha256": "e3b73131c57ad30eb54c8d2ebbcb7716607b0cd06bb8fc04a450da197509df96",
          "sha1": "743fa01711ad4bb9a3b1e824a0b8cda0698af747",
          "md5": "18e4d7830afae0a7c9fe743a3a48b72f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.63.aar",
          "url": "netsdk-1.0.1.63.aar",
          "size": 3294564,
          "sha512": "9976eb2fea9503cc20140be99a6191d9425343e32e627468f61eeb8441ad0e09260f3eaedb254ec3dc853dc8b8a8e6702579ba8d289f82407098aa59ff031373",
          "sha256": "e3b73131c57ad30eb54c8d2ebbcb7716607b0cd06bb8fc04a450da197509df96",
          "sha1": "743fa01711ad4bb9a3b1e824a0b8cda0698af747",
          "md5": "18e4d7830afae0a7c9fe743a3a48b72f"
        }
      ]
    }
  ]
}
