{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.77",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.77.aar",
          "url": "netsdk-1.0.1.77.aar",
          "size": 3305768,
          "sha512": "fe0696de5f8583764221b95f19772855820b4eeff72c882f0f941386b3fc0c1c785323d81811bffe8384496b250fbcbd94db7230ed0bfb982d65e500dbdf4a3c",
          "sha256": "824ec43f1649907ed447c27ad806ef1c63aa084a6f9bc3de142e63c359da3a8f",
          "sha1": "d7fef81de23712ab932cba96ce6e08d58e3b83af",
          "md5": "12e6f93f16c33d8cf81a0b56dee87942"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.77.aar",
          "url": "netsdk-1.0.1.77.aar",
          "size": 3305768,
          "sha512": "fe0696de5f8583764221b95f19772855820b4eeff72c882f0f941386b3fc0c1c785323d81811bffe8384496b250fbcbd94db7230ed0bfb982d65e500dbdf4a3c",
          "sha256": "824ec43f1649907ed447c27ad806ef1c63aa084a6f9bc3de142e63c359da3a8f",
          "sha1": "d7fef81de23712ab932cba96ce6e08d58e3b83af",
          "md5": "12e6f93f16c33d8cf81a0b56dee87942"
        }
      ]
    }
  ]
}
