{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.64",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.64.aar",
          "url": "netsdk-1.0.1.64.aar",
          "size": 3294679,
          "sha512": "c65502df38b0ac17577fe51c3ff53ee7017a51b5452805c7618c5ea00e4d98ce8ba4d3514608d30136ff8a7068b4e480bd6c6220283fc45aaff362895db59756",
          "sha256": "a4eb91ec8c2e39ecfbd7c40b9b71c70e879876b3fabba99f897194fb0c438e05",
          "sha1": "ec9d3c5dc3826672c48c1d60cdd105ffd532269b",
          "md5": "1fe07ad882d7dc327eadf156a030a07f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.64.aar",
          "url": "netsdk-1.0.1.64.aar",
          "size": 3294679,
          "sha512": "c65502df38b0ac17577fe51c3ff53ee7017a51b5452805c7618c5ea00e4d98ce8ba4d3514608d30136ff8a7068b4e480bd6c6220283fc45aaff362895db59756",
          "sha256": "a4eb91ec8c2e39ecfbd7c40b9b71c70e879876b3fabba99f897194fb0c438e05",
          "sha1": "ec9d3c5dc3826672c48c1d60cdd105ffd532269b",
          "md5": "1fe07ad882d7dc327eadf156a030a07f"
        }
      ]
    }
  ]
}
