{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.2.86",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.2.86.aar",
          "url": "netsdk-1.0.2.86.aar",
          "size": 3374570,
          "sha512": "11cd004e1497f92156e3c53b91bd71385a996bf5bdefdd449bc3bcf050f5da3955d4b2d8f2a3d9dff7cd97ac578de7a34bf63658795c2ec25273290658520e86",
          "sha256": "934201204d6d71dc7b2fa388c7c0bb1e77bbb6842c1d9b2d827be24247249573",
          "sha1": "5753179de9d5b80f00439858e04d82a796593ec4",
          "md5": "d6a1dee734e6050dbf5a59c44502796d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.2.86.aar",
          "url": "netsdk-1.0.2.86.aar",
          "size": 3374570,
          "sha512": "11cd004e1497f92156e3c53b91bd71385a996bf5bdefdd449bc3bcf050f5da3955d4b2d8f2a3d9dff7cd97ac578de7a34bf63658795c2ec25273290658520e86",
          "sha256": "934201204d6d71dc7b2fa388c7c0bb1e77bbb6842c1d9b2d827be24247249573",
          "sha1": "5753179de9d5b80f00439858e04d82a796593ec4",
          "md5": "d6a1dee734e6050dbf5a59c44502796d"
        }
      ]
    }
  ]
}
