{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.74",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.74.aar",
          "url": "netsdk-1.0.1.74.aar",
          "size": 3303861,
          "sha512": "4a68a5ab4f8d22d93d49f113842e7857abb6bec1a26a142b45e265798108dc6fa8e53beeb972e9591400cb964aca44295cd272b714faab531ae56c4142c18eb2",
          "sha256": "e35dba2ab654a48855db876b52bf1a2ab4b96fcd5d663705559cb8ec61df894a",
          "sha1": "76667931275308dce7436b2f210387f544b9b4f9",
          "md5": "5b691130175a5d33d98cb9464a4aeb8b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.74.aar",
          "url": "netsdk-1.0.1.74.aar",
          "size": 3303861,
          "sha512": "4a68a5ab4f8d22d93d49f113842e7857abb6bec1a26a142b45e265798108dc6fa8e53beeb972e9591400cb964aca44295cd272b714faab531ae56c4142c18eb2",
          "sha256": "e35dba2ab654a48855db876b52bf1a2ab4b96fcd5d663705559cb8ec61df894a",
          "sha1": "76667931275308dce7436b2f210387f544b9b4f9",
          "md5": "5b691130175a5d33d98cb9464a4aeb8b"
        }
      ]
    }
  ]
}
