{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.80",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.80.aar",
          "url": "netsdk-1.0.1.80.aar",
          "size": 3313555,
          "sha512": "52a3bb38aa5935409a7a6f64bf31f291738ca551a147206688bad40a74b7c50ce3c0252848c936a164ab56f87521b63344c63f5315bc38dad55343a250e6a0dd",
          "sha256": "cf303502359dc79a4333e6da107c3a9aac4e07944f1e24e976f58cc8705a500e",
          "sha1": "97b51808f95d1ddee024d558b9de8f40d1e09392",
          "md5": "e9fedf9ef8407fdaacc6da223f93b916"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.80.aar",
          "url": "netsdk-1.0.1.80.aar",
          "size": 3313555,
          "sha512": "52a3bb38aa5935409a7a6f64bf31f291738ca551a147206688bad40a74b7c50ce3c0252848c936a164ab56f87521b63344c63f5315bc38dad55343a250e6a0dd",
          "sha256": "cf303502359dc79a4333e6da107c3a9aac4e07944f1e24e976f58cc8705a500e",
          "sha1": "97b51808f95d1ddee024d558b9de8f40d1e09392",
          "md5": "e9fedf9ef8407fdaacc6da223f93b916"
        }
      ]
    }
  ]
}
