{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.72",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.72.aar",
          "url": "netsdk-1.0.1.72.aar",
          "size": 3299100,
          "sha512": "489d9c75badf122362a687857c8007b16957aa7ae84b59053f379d9bc456a6aa2db7ad2d97e7da56ea619379fcea77d5cf723ef3d7b8a59851bcaef2874a1cbf",
          "sha256": "341d626121c85bd8ec51a230aa87231168ed001c1171ec8df60565e06580ebc6",
          "sha1": "ba2a0e8fe86564356545d7cb887349fbc469f72e",
          "md5": "912c8218b3853ff77c8165d7d0f5b7e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.72.aar",
          "url": "netsdk-1.0.1.72.aar",
          "size": 3299100,
          "sha512": "489d9c75badf122362a687857c8007b16957aa7ae84b59053f379d9bc456a6aa2db7ad2d97e7da56ea619379fcea77d5cf723ef3d7b8a59851bcaef2874a1cbf",
          "sha256": "341d626121c85bd8ec51a230aa87231168ed001c1171ec8df60565e06580ebc6",
          "sha1": "ba2a0e8fe86564356545d7cb887349fbc469f72e",
          "md5": "912c8218b3853ff77c8165d7d0f5b7e6"
        }
      ]
    }
  ]
}
