{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.65",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.65.aar",
          "url": "netsdk-1.0.1.65.aar",
          "size": 3299094,
          "sha512": "c31e94e90cba9421d182436cfcb5f2c2cd17c872ddf753abf355e72b65333bf3a46c1b7477a7b435bc47c19299816a9a4a604bb011f09cec62509741d81bda7b",
          "sha256": "f346b29d3a03c2778332fe1b35609f37d8ed21093b36c0ee5787c399e20532c0",
          "sha1": "456bc2da6399fddaaf2d4d4975ffb706dd65d4b7",
          "md5": "6d0f61e9ca75095fdba58d8b733d68a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.65.aar",
          "url": "netsdk-1.0.1.65.aar",
          "size": 3299094,
          "sha512": "c31e94e90cba9421d182436cfcb5f2c2cd17c872ddf753abf355e72b65333bf3a46c1b7477a7b435bc47c19299816a9a4a604bb011f09cec62509741d81bda7b",
          "sha256": "f346b29d3a03c2778332fe1b35609f37d8ed21093b36c0ee5787c399e20532c0",
          "sha1": "456bc2da6399fddaaf2d4d4975ffb706dd65d4b7",
          "md5": "6d0f61e9ca75095fdba58d8b733d68a2"
        }
      ]
    }
  ]
}
