{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.73",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.73.aar",
          "url": "netsdk-1.0.1.73.aar",
          "size": 3299100,
          "sha512": "dc18a70b153dc7e5f6e72b6eb4f3811be7ab6ab497ad6b66c0cc9714832ccf866fb5f654e9582438cfd4cdbfbd8d5e999d6d89d68aa86d9a9ac414f62574506a",
          "sha256": "9503f1f2a8852fd2b484e3fca625e24cf09ec90606b3a5a06ed2119f3d843548",
          "sha1": "1c233def90aebba79f619b02e78449a0b0ed393d",
          "md5": "e34c66f6bfafa92274154118a2ba3506"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.73.aar",
          "url": "netsdk-1.0.1.73.aar",
          "size": 3299100,
          "sha512": "dc18a70b153dc7e5f6e72b6eb4f3811be7ab6ab497ad6b66c0cc9714832ccf866fb5f654e9582438cfd4cdbfbd8d5e999d6d89d68aa86d9a9ac414f62574506a",
          "sha256": "9503f1f2a8852fd2b484e3fca625e24cf09ec90606b3a5a06ed2119f3d843548",
          "sha1": "1c233def90aebba79f619b02e78449a0b0ed393d",
          "md5": "e34c66f6bfafa92274154118a2ba3506"
        }
      ]
    }
  ]
}
