{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.2.88",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.2.88.aar",
          "url": "netsdk-1.0.2.88.aar",
          "size": 3380956,
          "sha512": "71b7cf14663acfeb567d46784e25060803837957b0ed4bcaf655d6c0a7df415efe91fd8452c08b88d0670fc2204994cfbc5eb8070a515837e363d3e68e7af966",
          "sha256": "e53a0c836dc9d0d291c4a927d2a1ca981b934d20288df39ef32df9fb9b55d411",
          "sha1": "d6a515ae9978d21418c13f6e475fd5d5af7c75f6",
          "md5": "28f973a55b46537b6e8722fe2698d564"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.2.88.aar",
          "url": "netsdk-1.0.2.88.aar",
          "size": 3380956,
          "sha512": "71b7cf14663acfeb567d46784e25060803837957b0ed4bcaf655d6c0a7df415efe91fd8452c08b88d0670fc2204994cfbc5eb8070a515837e363d3e68e7af966",
          "sha256": "e53a0c836dc9d0d291c4a927d2a1ca981b934d20288df39ef32df9fb9b55d411",
          "sha1": "d6a515ae9978d21418c13f6e475fd5d5af7c75f6",
          "md5": "28f973a55b46537b6e8722fe2698d564"
        }
      ]
    }
  ]
}
