{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.1.79",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.79.aar",
          "url": "netsdk-1.0.1.79.aar",
          "size": 3299880,
          "sha512": "660fdb4ff9444e8829b04cd67b23453743848b928b7a415038d47d275903341299d7e8e311de5b7fed854724a2c0164a46430cdf35856ddc658fb44156c7e781",
          "sha256": "7439e9dfaca37405dd460b908ca54d44597e884c53ed2f0b61818b06f1526e42",
          "sha1": "e3c7b9fbd44dc4cb2c51de1a47b3b341dcb3778c",
          "md5": "e31556423969fe2741d746fc7128bc5d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.1.79.aar",
          "url": "netsdk-1.0.1.79.aar",
          "size": 3299880,
          "sha512": "660fdb4ff9444e8829b04cd67b23453743848b928b7a415038d47d275903341299d7e8e311de5b7fed854724a2c0164a46430cdf35856ddc658fb44156c7e781",
          "sha256": "7439e9dfaca37405dd460b908ca54d44597e884c53ed2f0b61818b06f1526e42",
          "sha1": "e3c7b9fbd44dc4cb2c51de1a47b3b341dcb3778c",
          "md5": "e31556423969fe2741d746fc7128bc5d"
        }
      ]
    }
  ]
}
