{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.2.89",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.2.89.aar",
          "url": "netsdk-1.0.2.89.aar",
          "size": 3380956,
          "sha512": "aa7147c97328d8319508bd0c0d1ae3ce740163e0818f40ba12a13c04b460412b1a0e4c0c81b82a3c0e706fef8419a10b095a1c1f018a9c074548deb9a37f4a7f",
          "sha256": "6a45b3fbea34ea511a4c92305feb642a427493e8600d1e77229cea9d4138eb3a",
          "sha1": "8f2b32ede698621bab1afda290cc9dffbf2b27dd",
          "md5": "e7ac6c4f869fcdb3fa0c844b1ca19332"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.2.89.aar",
          "url": "netsdk-1.0.2.89.aar",
          "size": 3380956,
          "sha512": "aa7147c97328d8319508bd0c0d1ae3ce740163e0818f40ba12a13c04b460412b1a0e4c0c81b82a3c0e706fef8419a10b095a1c1f018a9c074548deb9a37f4a7f",
          "sha256": "6a45b3fbea34ea511a4c92305feb642a427493e8600d1e77229cea9d4138eb3a",
          "sha1": "8f2b32ede698621bab1afda290cc9dffbf2b27dd",
          "md5": "e7ac6c4f869fcdb3fa0c844b1ca19332"
        }
      ]
    }
  ]
}
