{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irtek",
    "module": "netsdk",
    "version": "1.0.2.87",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.2.87.aar",
          "url": "netsdk-1.0.2.87.aar",
          "size": 3381223,
          "sha512": "f55c057431095c6c461681e3512e5957a2f6af27ea34b6f4d3c6c1f4568fade04c21836d6833b892a07d53f57eb4069d0616f16d6c73fc9753f954e2aacae8a3",
          "sha256": "9ac716b4deff51cf8902d4f80c5c318232fc21a306b6826e338e182e66efdf56",
          "sha1": "25834e4d15b414371a00bd68bd542d2139ff3ea2",
          "md5": "c82b5fdd99ccc92561d65ebcba643133"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.arthenica",
          "module": "ffmpeg-kit-min-gpl",
          "version": {
            "requires": "5.1.LTS"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "netsdk-1.0.2.87.aar",
          "url": "netsdk-1.0.2.87.aar",
          "size": 3381223,
          "sha512": "f55c057431095c6c461681e3512e5957a2f6af27ea34b6f4d3c6c1f4568fade04c21836d6833b892a07d53f57eb4069d0616f16d6c73fc9753f954e2aacae8a3",
          "sha256": "9ac716b4deff51cf8902d4f80c5c318232fc21a306b6826e338e182e66efdf56",
          "sha1": "25834e4d15b414371a00bd68bd542d2139ff3ea2",
          "md5": "c82b5fdd99ccc92561d65ebcba643133"
        }
      ]
    }
  ]
}
